# Generated by Django 3.2.5 on 2021-07-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('problem_pic', models.FileField(null=True, upload_to='')),
                ('problem_text', models.TextField(null=True)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('telegram_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts_count', models.IntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.tguser')),
            ],
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('problem_pic__isnull', False), ('problem_text__isnull', False), _connector='OR'), name='check_problem_not_null'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['task', 'user', 'solved'], name='db_taskatte_task_id_474aa8_idx'),
        ),
    ]
