# Generated by Django 3.2.5 on 2021-07-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='answer',
        ),
        migrations.AddField(
            model_name='task',
            name='answer_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='task',
            name='answer_text',
            field=models.TextField(null=True),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('answer_pic__isnull', False), ('answer_text__isnull', False), _connector='OR'), name='check_answer_not_null'),
        ),
    ]
