# Generated by Django 3.2.5 on 2021-07-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20210725_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link_to_lesson',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
