# Generated by Django 3.2.5 on 2021-07-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_task_link_to_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattempt',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='db.task'),
        ),
    ]
